perceptron:
  lr: 0.0003                  # step size (below threshold)
  k: 3.0                      # threshold on stability
  suppress_right_field: true  # ignore interaction on the right in field comparison against threshold
  epochs: 10
