defaults:
  - /../hydra@_here_
  - /../base@_here_

simulation:
  share_J: false            # if true, replicas share J
  chained: true             # if true, replicas interact in a chain
  J_D: 0.3               
  y: 5                      # number of replicas
  k: 1.6                    # strength of coupling between replicas
  left_field: ones          # if null, no field
  right_field: minus_ones   # if null, no field
  h: 2.0                    # external field strength
  hebb:
    skip: false
    params:
      lr: 0.001
      max_steps: 10
      reinit: true
      seed: 0
  anneal_k: null            # annealing multiplier. if null, no annealing
