defaults:
  - /../hydra@_here_
  - /../base@_here_

simulation:
  J_D: 0.3               
  share_J: false         # if true, replicas share J
  chained: true         # if true, replicas interact in a chain
  y: 5                   # number of replicas
  k: 1.6                 # strength of coupling between replicas
  anneal_k: null         # if null, no annealing
  left_field: ones    # if null, no field
  right_field: minus_ones   # if null, no field
  h: 0.7                 # external field strength
