hydra:
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - name
  run:
    dir: outputs/${name}/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d-%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}

name: prova

simulation:
  N: 1000            
  symmetric: false     
  J_D: 0.7          
  max_iterations: 1000000
  log_interval: 1000
  seed: 42

stability:
  num_steps: 10000
  skip: true

logging:
  level: INFO
