hydra:
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - name
  run:
    dir: outputs/${name}/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d-%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}

name: prova

simulation:
  N: 100            
  symmetric: false     
  J_D: 0.0          
  max_iterations: 100000
  log_interval: 100
  seed: 42

stability:
  num_steps: 5000

logging:
  level: INFO
