hydra:
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - name
  run:
    dir: outputs/${name}/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d-%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}

logging:
  level: INFO