defaults:
  - /hydra@_here_
  - base

simulation:               
  same_couplings: true  # if true, replicas share J
  y: 5                  # number of replicas
  k: 0.2                # strength of coupling between replicas
  anneal_k: null         # if null, no annealing
