hydra:
  job:
    chdir: False
    config:
      override_dirname:
        exclude_keys:
          - name
  run:
    dir: outputs/${name}/${now:%Y-%m-%d-%H-%M-%S}
  sweep:
    dir: multirun/${name}/${now:%Y-%m-%d-%H-%M-%S}
    subdir: cfg:${hydra.job.override_dirname}

name: prova

simulation:
  N: 1000     
  J_D: 0.7                 
  symmetric: false     
  same_couplings: true
  y: 2
  k: 0.0
  max_iterations: 1000000
  check_convergence_interval: 1000
  log_interval: 1000
  seed: 42

stability:
  skip: false
  num_steps: 20000
  check_convergence_interval: 250
  log_interval: 250
  seed: 42

logging:
  level: INFO
