defaults:
  - /hydra@_here_

name: prova

simulation:
  N: 1000     
  J_D: 0.7                 
  symmetric: false     
  max_iterations: 1000000
  check_convergence_interval: 1000
  log_interval: 1000
  seed: 42

stability:
  skip: false
  num_steps: 20000
  check_convergence_interval: 250
  log_interval: 250
  seed: 42
